intersections = [
    # AREVALO / VILLA
    {
        "id": "villa - 1",
        "y": 10.688897,
        "x": 122.516400,
        "name": "Osmena St - Jocson St",
    },
    {
        "id": "villa - 2",
        "y": 10.688957,
        "x": 122.521095,
        "name": "Iloilo Circumrferential Rd 1 - Jocson St",
    },
    {
        "id": "villa - 3",
        "y": 10.688729,
        "x": 122.526827,
        "name": "Jocson St - Quezon St",
    },
    {"id": "villa - 4", "y": 10.687044, "x": 122.516604, "name": "Quezon St - Yulo Dr"},
    {
        "id": "villa - 5",
        "y": 10.682915,
        "x": 122.494799,
        "name": "Molo Blvd - Santa Cruz St",
    },
    {
        "id": "villa - 6",
        "y": 10.693689,
        "x": 122.498629,
        "name": "Osmena St - Pakiad St",
    },
    {"id": "villa - 7", "y": 10.694791, "x": 122.498790, "name": "Pakiad Rd"},
    # MOLO
    {
        "id": "Molo - 3",
        "y": 10.697347,
        "x": 122.543396,
        "name": "Locsin St - San Marcos St.",
    },
    {
        "id": "Molo - 4",
        "y": 10.695993,
        "x": 122.544452,
        "name": "Locsin St. - M.H Del Pilar St. 2",
    },
    {
        "id": "Molo - 5",
        "y": 10.694449,
        "x": 122.545638,
        "name": "Locsin St. - Timawa St.",
    },
    {
        "id": "Molo - 6",
        "y": 10.692042,
        "x": 122.549359,
        "name": "Locsin St. - Baluarte - Calumpag - Villa - Oton Blvd",
    },
    {
        "id": "Molo - 7",
        "y": 10.699246,
        "x": 122.549446,
        "name": "San Marcos St. - MH del Pilar St. 1 (Rotunda)",
    },
    {
        "id": "Molo - 8",
        "y": 10.699231,
        "x": 122.549295,
        "name": "San Marcos St. - MH del Pilar St. 1 (Rotunda)",
    },
    {"id": "Molo - 9", "y": 10.698880, "x": 122.549361, "name": "M.H Del Pilar St. 2"},
    {"id": "Molo - 10", "y": 10.698959, "x": 122.549522, "name": "M.H Del Pilar St. 2"},
    # CITY PROPER
    {
        "id": "Proper - 1",
        "y": 10.699766,
        "x": 122.554176,
        "name": "Gen Luna St - Infante St",
    },
    {
        "id": "Proper - 2",
        "y": 10.696536,
        "x": 122.554848,
        "name": "Delgado St - Infante St",
    },
    {
        "id": "Proper - 3",
        "y": 10.694484,
        "x": 122.555064,
        "name": "Rizal St - Infante St",
    },
    {
        "id": "Proper - 4",
        "y": 10.692782,
        "x": 122.555299,
        "name": "Baluarte - Calumpang - Villa - Oton Blvd - Infante St",
    },
    {
        "id": "Proper - 5",
        "y": 10.693734,
        "x": 122.556639,
        "name": "Baluarte - Calumpang - Villa - Oton Blvd - Rizal St",
    },
    {
        "id": "Proper - 6",
        "y": 10.693333,
        "x": 122.558918,
        "name": "Ledesma St - Rizal St",
    },
    {
        "id": "Proper - 7",
        "y": 10.701768,
        "x": 122.568323,
        "name": "Gen Luna St - Bonifacio Dr",
    },
    {
        "id": "Proper - 8",
        "y": 10.701513,
        "x": 122.569120,
        "name": "Gen Luna St - Ruperto Montinola St",
    },
    {
        "id": "Proper - 9",
        "y": 10.701726,
        "x": 122.569779,
        "name": "Gen Luna St - Muelle Loney St",
    },
    {
        "id": "Proper - 10",
        "y": 10.697813,
        "x": 122.569103,
        "name": "Delgado St - Ruperto Montinola St Left",
    },
    {
        "id": "Proper - 11",
        "y": 10.696552,
        "x": 122.569018,
        "name": "Ledesma St - Ruperto Montinola St",
    },
    {
        "id": "Proper - 12",
        "y": 10.697060,
        "x": 122.570971,
        "name": "Arroyo St - Muelle Loney St",
    },
    {
        "id": "Proper - 13",
        "y": 10.692725,
        "x": 122.572940,
        "name": "JM Basa St - De la Rama St",
    },
    {
        "id": "Proper - 14",
        "y": 10.691733,
        "x": 122.573801,
        "name": "JM Basa St - Rizal St",
    },
    {
        "id": "Proper - 15",
        "y": 10.689938,
        "x": 122.576432,
        "name": "General Hughes St - Duran St",
    },
    {"id": "Proper - 16", "y": 10.693996, "x": 122.579428, "name": "Duran St"},
    {
        "id": "Proper - 17",
        "y": 10.696937,
        "x": 122.577236,
        "name": "Dela Rama St - Blumentritt",
    },
    {
        "id": "Proper - 18",
        "y": 10.697315,
        "x": 122.575792,
        "name": "Muelle Loney St - Blumentritt Left",
    },
    {
        "id": "Proper - 19",
        "y": 10.696437,
        "x": 122.579052,
        "name": "Muelle Loney St - Blumentritt Right",
    },
    {"id": "Proper - 20", "y": 10.697963, "x": 122.578372, "name": "De la Rama St"},
    {
        "id": "Proper - 21",
        "y": 10.692842,
        "x": 122.582764,
        "name": "Fort San Pedro Dr - Muelle Loney St",
    },
    {
        "id": "Proper - 22",
        "y": 10.688291,
        "x": 122.579310,
        "name": "Fort San Pedro Dr - General Hughes St",
    },
    {
        "id": "Proper - 23",
        "y": 10.696552,
        "x": 122.569018,
        "name": "Arroyo St - Ruperto Montinola St",
    },
    {
        "id": "Proper - 24",
        "y": 10.697813,
        "x": 122.569103,
        "name": "Delgado St - Ruperto Montinola St Right",
    },
]

# --- MASTER ROADS ---
# Consolidated list of road segments
roads = [
    # Arevalo Internal
    {
        "A": "villa - 1",
        "B": "villa - 6",
        "distance": 2000,
        "lanes": 2,
        "oneway": False,
        "name": "Osmena St",
    },
    {
        "A": "villa - 1",
        "B": "villa - 4",
        "distance": 200,
        "lanes": 2,
        "oneway": False,
        "name": "Yulo Dr",
    },
    {
        "A": "villa - 3",
        "B": "villa - 4",
        "distance": 1100,
        "lanes": 2,
        "oneway": False,
        "name": "Quezon St",
    },
    {
        "A": "villa - 1",
        "B": "villa - 2",
        "distance": 500,
        "lanes": 2,
        "oneway": False,
        "name": "Jocson St",
    },
    {
        "A": "villa - 2",
        "B": "villa - 3",
        "distance": 650,
        "lanes": 2,
        "oneway": False,
        "name": "Circumferential Rd 1",
    },
    {
        "A": "villa - 7",
        "B": "villa - 6",
        "distance": 120,
        "lanes": 1,
        "oneway": False,
        "name": "Pakiad Rd",
    },
    # Molo Internal & District Connections
    {
        "A": "Molo - 3",
        "B": "villa - 3",
        "distance": 2100,
        "lanes": 2,
        "oneway": False,
        "name": "Molo - Arevalo Connect",
    },
    {
        "A": "Molo - 3",
        "B": "Molo - 4",
        "distance": 190,
        "lanes": 2,
        "oneway": False,
        "name": "Locsin St",
    },
    {
        "A": "Molo - 4",
        "B": "Molo - 5",
        "distance": 220,
        "lanes": 2,
        "oneway": False,
        "name": "Locsin St",
    },
    {
        "A": "Molo - 4",
        "B": "Molo - 9",
        "distance": 650,
        "lanes": 2,
        "oneway": False,
        "name": "M.H Del Pilar",
    },
    {
        "A": "Molo - 5",
        "B": "Molo - 6",
        "distance": 500,
        "lanes": 2,
        "oneway": False,
        "name": "Locsin St",
    },
    {
        "A": "Molo - 7",
        "B": "Molo - 8",
        "distance": 16,
        "lanes": 2,
        "oneway": True,
        "name": "Rotunda",
    },
    {
        "A": "Molo - 8",
        "B": "Molo - 3",
        "distance": 700,
        "lanes": 4,
        "oneway": True,
        "name": "San Marcos St",
    },
    {
        "A": "Molo - 8",
        "B": "Molo - 9",
        "distance": 42,
        "lanes": 1,
        "oneway": True,
        "name": "M.H Del Pilar",
    },
    {
        "A": "Molo - 9",
        "B": "Molo - 10",
        "distance": 20,
        "lanes": 4,
        "oneway": True,
        "name": "M.H Del Pilar",
    },
    {
        "A": "Molo - 10",
        "B": "Proper - 1",
        "distance": 500,
        "lanes": 2,
        "oneway": True,
        "name": "Molo - Proper Connect",
    },
    {
        "A": "Molo - 10",
        "B": "Molo - 7",
        "distance": 38,
        "lanes": 1,
        "oneway": True,
        "name": "M.H Del Pilar",
    },
    {
        "A": "Proper - 1",
        "B": "Molo - 7",
        "distance": 550,
        "lanes": 4,
        "oneway": True,
        "name": "Gen Luna - Molo Connect",
    },
    {
        "A": "Molo - 6",
        "B": "villa - 5",
        "distance": 6600,
        "lanes": 2,
        "oneway": False,
        "name": "Molo Blvd",
    },
    {
        "A": "Molo - 5",
        "B": "Proper - 2",
        "distance": 1100,
        "lanes": 2,
        "oneway": False,
        "name": "Timawa St",
    },
    {
        "A": "Molo - 6",
        "B": "Proper - 4",
        "distance": 650,
        "lanes": 2,
        "oneway": False,
        "name": "Molo Blvd 2",
    },
    # City Proper Internal
    {
        "A": "Proper - 1",
        "B": "Proper - 2",
        "distance": 350,
        "lanes": 2,
        "oneway": False,
        "name": "Infante St 1",
    },
    {
        "A": "Proper - 2",
        "B": "Proper - 3",
        "distance": 230,
        "lanes": 2,
        "oneway": False,
        "name": "Infante St 2",
    },
    {
        "A": "Proper - 3",
        "B": "Proper - 4",
        "distance": 190,
        "lanes": 2,
        "oneway": True,
        "name": "Infante St 3",
    },
    {
        "A": "Proper - 4",
        "B": "Proper - 5",
        "distance": 180,
        "lanes": 2,
        "oneway": True,
        "name": "Baluarte - Oton Blvd",
    },
    {
        "A": "Proper - 5",
        "B": "Proper - 3",
        "distance": 190,
        "lanes": 2,
        "oneway": True,
        "name": "Rizal St 1",
    },
    {
        "A": "Proper - 5",
        "B": "Proper - 6",
        "distance": 260,
        "lanes": 2,
        "oneway": False,
        "name": "Rizal St 2",
    },
    {
        "A": "Proper - 6",
        "B": "Proper - 14",
        "distance": 1700,
        "lanes": 2,
        "oneway": False,
        "name": "Rizal St 3",
    },
    {
        "A": "Proper - 6",
        "B": "Proper - 11",
        "distance": 1160,
        "lanes": 2,
        "oneway": False,
        "name": "Ledesma St",
    },
    {
        "A": "Proper - 1",
        "B": "Proper - 7",
        "distance": 1550,
        "lanes": 2,
        "oneway": False,
        "name": "Gen Luna St 1",
    },
    {
        "A": "Proper - 7",
        "B": "Proper - 8",
        "distance": 95,
        "lanes": 2,
        "oneway": False,
        "name": "Gen Luna St 2",
    },
    {
        "A": "Proper - 8",
        "B": "Proper - 9",
        "distance": 75,
        "lanes": 12,
        "oneway": False,
        "name": "Gen Luna St 3",
    },
    {
        "A": "Proper - 8",
        "B": "Proper - 10",
        "distance": 400,
        "lanes": 2,
        "oneway": True,
        "name": "Ruperto Montinola St 1",
    },
    {
        "A": "Proper - 10",
        "B": "Proper - 11",
        "distance": 130,
        "lanes": 2,
        "oneway": True,
        "name": "Ruperto Montinola St 2",
    },
    {
        "A": "Proper - 2",
        "B": "Proper - 10",
        "distance": 1550,
        "lanes": 2,
        "oneway": False,
        "name": "Delgado St",
    },
    {
        "A": "Proper - 12",
        "B": "Proper - 23",
        "distance": 200,
        "lanes": 1,
        "oneway": False,
        "name": "Arroyo St",
    },
    {
        "A": "Proper - 11",
        "B": "Proper - 13",
        "distance": 600,
        "lanes": 2,
        "oneway": True,
        "name": "JM Basa St 1",
    },
    {
        "A": "Proper - 13",
        "B": "Proper - 14",
        "distance": 150,
        "lanes": 2,
        "oneway": False,
        "name": "JM Basa St 2",
    },
    {
        "A": "Proper - 14",
        "B": "Proper - 15",
        "distance": 350,
        "lanes": 2,
        "oneway": False,
        "name": "General Hughes St 1",
    },
    {
        "A": "Proper - 15",
        "B": "Proper - 16",
        "distance": 550,
        "lanes": 1,
        "oneway": False,
        "name": "Duran St",
    },
    {
        "A": "Proper - 15",
        "B": "Proper - 22",
        "distance": 350,
        "lanes": 2,
        "oneway": False,
        "name": "General Hughes St 2",
    },
    {
        "A": "Proper - 13",
        "B": "Proper - 17",
        "distance": 650,
        "lanes": 1,
        "oneway": False,
        "name": "Dela Rama St 1",
    },
    {
        "A": "Proper - 17",
        "B": "Proper - 20",
        "distance": 170,
        "lanes": 1,
        "oneway": False,
        "name": "Dela Rama St 2",
    },
    {
        "A": "Proper - 17",
        "B": "Proper - 18",
        "distance": 160,
        "lanes": 1,
        "oneway": False,
        "name": "Blumentritt 1",
    },
    {
        "A": "Proper - 17",
        "B": "Proper - 19",
        "distance": 220,
        "lanes": 1,
        "oneway": False,
        "name": "Blumentritt 2",
    },
    {
        "A": "Proper - 9",
        "B": "Proper - 12",
        "distance": 550,
        "lanes": 2,
        "oneway": False,
        "name": "Muelle Loney St 1",
    },
    {
        "A": "Proper - 12",
        "B": "Proper - 18",
        "distance": 900,
        "lanes": 2,
        "oneway": False,
        "name": "Muelle Loney St 2",
    },
    {
        "A": "Proper - 18",
        "B": "Proper - 19",
        "distance": 800,
        "lanes": 2,
        "oneway": False,
        "name": "Muelle Loney St 3",
    },
    {
        "A": "Proper - 19",
        "B": "Proper - 21",
        "distance": 550,
        "lanes": 2,
        "oneway": False,
        "name": "Muelle Loney St 4",
    },
    {
        "A": "Proper - 21",
        "B": "Proper - 22",
        "distance": 700,
        "lanes": 2,
        "oneway": False,
        "name": "Fort San Pedro Dr",
    },
    {
        "A": "Proper - 13",
        "B": "Proper - 23",
        "distance": 600,
        "lanes": 2,
        "oneway": True,
        "name": "JM Basa St (Rev)",
    },
    {
        "A": "Proper - 23",
        "B": "Proper - 24",
        "distance": 130,
        "lanes": 2,
        "oneway": True,
        "name": "Ruperto Montinola 2 (Rev)",
    },
    {
        "A": "Proper - 24",
        "B": "Proper - 8",
        "distance": 400,
        "lanes": 2,
        "oneway": True,
        "name": "Ruperto Montinola 1 (Rev)",
    },
]
