# Auto-generated TNTP-style data from arevalo.py

# Node Mapping Reference:
# 1: Molo - 6
# 2: mandurriao - 8
# 3: villa - 1
# 4: villa - 2
# 5: villa - 3
# 6: villa - 4
# 7: villa - 5
# 8: villa - 6
# 9: villa - 7

network_data = [
    {'init_node': 3, 'term_node': 8, 'capacity': 3600.0, 'length': 2.0, 'free_flow_time': 0.0, 'b': 0.15, 'power': 4, 'speed': 0, 'toll': 0, 'link_type': 1},
    {'init_node': 8, 'term_node': 3, 'capacity': 3600.0, 'length': 2.0, 'free_flow_time': 0.0, 'b': 0.15, 'power': 4, 'speed': 0, 'toll': 0, 'link_type': 1},
    {'init_node': 7, 'term_node': 1, 'capacity': 1800.0, 'length': 6.6, 'free_flow_time': 0.0, 'b': 0.15, 'power': 4, 'speed': 0, 'toll': 0, 'link_type': 1},
    {'init_node': 1, 'term_node': 7, 'capacity': 1800.0, 'length': 6.6, 'free_flow_time': 0.0, 'b': 0.15, 'power': 4, 'speed': 0, 'toll': 0, 'link_type': 1},
    {'init_node': 3, 'term_node': 6, 'capacity': 3600.0, 'length': 0.2, 'free_flow_time': 0.0, 'b': 0.15, 'power': 4, 'speed': 0, 'toll': 0, 'link_type': 1},
    {'init_node': 6, 'term_node': 3, 'capacity': 3600.0, 'length': 0.2, 'free_flow_time': 0.0, 'b': 0.15, 'power': 4, 'speed': 0, 'toll': 0, 'link_type': 1},
    {'init_node': 5, 'term_node': 6, 'capacity': 3600.0, 'length': 1.1, 'free_flow_time': 0.0, 'b': 0.15, 'power': 4, 'speed': 0, 'toll': 0, 'link_type': 1},
    {'init_node': 6, 'term_node': 5, 'capacity': 3600.0, 'length': 1.1, 'free_flow_time': 0.0, 'b': 0.15, 'power': 4, 'speed': 0, 'toll': 0, 'link_type': 1},
    {'init_node': 4, 'term_node': 2, 'capacity': 3600.0, 'length': 2.4, 'free_flow_time': 0.0, 'b': 0.15, 'power': 4, 'speed': 0, 'toll': 0, 'link_type': 1},
    {'init_node': 2, 'term_node': 4, 'capacity': 3600.0, 'length': 2.4, 'free_flow_time': 0.0, 'b': 0.15, 'power': 4, 'speed': 0, 'toll': 0, 'link_type': 1},
    {'init_node': 3, 'term_node': 4, 'capacity': 3600.0, 'length': 0.5, 'free_flow_time': 0.0, 'b': 0.15, 'power': 4, 'speed': 0, 'toll': 0, 'link_type': 1},
    {'init_node': 4, 'term_node': 3, 'capacity': 3600.0, 'length': 0.5, 'free_flow_time': 0.0, 'b': 0.15, 'power': 4, 'speed': 0, 'toll': 0, 'link_type': 1},
    {'init_node': 4, 'term_node': 5, 'capacity': 3600.0, 'length': 0.65, 'free_flow_time': 0.0, 'b': 0.15, 'power': 4, 'speed': 0, 'toll': 0, 'link_type': 1},
    {'init_node': 5, 'term_node': 4, 'capacity': 3600.0, 'length': 0.65, 'free_flow_time': 0.0, 'b': 0.15, 'power': 4, 'speed': 0, 'toll': 0, 'link_type': 1},
    {'init_node': 9, 'term_node': 8, 'capacity': 1800.0, 'length': 0.12, 'free_flow_time': 0.0, 'b': 0.15, 'power': 4, 'speed': 0, 'toll': 0, 'link_type': 1},
    {'init_node': 8, 'term_node': 9, 'capacity': 1800.0, 'length': 0.12, 'free_flow_time': 0.0, 'b': 0.15, 'power': 4, 'speed': 0, 'toll': 0, 'link_type': 1},
]

demand_data = [
    {'init_node': 1, 'term_node': 1, 'demand': 0.0},
    {'init_node': 1, 'term_node': 2, 'demand': 0.0},
    {'init_node': 1, 'term_node': 3, 'demand': 0.0},
    {'init_node': 1, 'term_node': 4, 'demand': 0.0},
    {'init_node': 1, 'term_node': 5, 'demand': 0.0},
    {'init_node': 1, 'term_node': 6, 'demand': 0.0},
    {'init_node': 1, 'term_node': 7, 'demand': 0.0},
    {'init_node': 1, 'term_node': 8, 'demand': 0.0},
    {'init_node': 1, 'term_node': 9, 'demand': 0.0},
    {'init_node': 2, 'term_node': 1, 'demand': 0.0},
    {'init_node': 2, 'term_node': 2, 'demand': 0.0},
    {'init_node': 2, 'term_node': 3, 'demand': 0.0},
    {'init_node': 2, 'term_node': 4, 'demand': 0.0},
    {'init_node': 2, 'term_node': 5, 'demand': 0.0},
    {'init_node': 2, 'term_node': 6, 'demand': 0.0},
    {'init_node': 2, 'term_node': 7, 'demand': 0.0},
    {'init_node': 2, 'term_node': 8, 'demand': 0.0},
    {'init_node': 2, 'term_node': 9, 'demand': 0.0},
    {'init_node': 3, 'term_node': 1, 'demand': 0.0},
    {'init_node': 3, 'term_node': 2, 'demand': 0.0},
    {'init_node': 3, 'term_node': 3, 'demand': 0.0},
    {'init_node': 3, 'term_node': 4, 'demand': 0.0},
    {'init_node': 3, 'term_node': 5, 'demand': 0.0},
    {'init_node': 3, 'term_node': 6, 'demand': 0.0},
    {'init_node': 3, 'term_node': 7, 'demand': 0.0},
    {'init_node': 3, 'term_node': 8, 'demand': 0.0},
    {'init_node': 3, 'term_node': 9, 'demand': 0.0},
    {'init_node': 4, 'term_node': 1, 'demand': 0.0},
    {'init_node': 4, 'term_node': 2, 'demand': 0.0},
    {'init_node': 4, 'term_node': 3, 'demand': 0.0},
    {'init_node': 4, 'term_node': 4, 'demand': 0.0},
    {'init_node': 4, 'term_node': 5, 'demand': 0.0},
    {'init_node': 4, 'term_node': 6, 'demand': 0.0},
    {'init_node': 4, 'term_node': 7, 'demand': 0.0},
    {'init_node': 4, 'term_node': 8, 'demand': 0.0},
    {'init_node': 4, 'term_node': 9, 'demand': 0.0},
    {'init_node': 5, 'term_node': 1, 'demand': 0.0},
    {'init_node': 5, 'term_node': 2, 'demand': 0.0},
    {'init_node': 5, 'term_node': 3, 'demand': 0.0},
    {'init_node': 5, 'term_node': 4, 'demand': 0.0},
    {'init_node': 5, 'term_node': 5, 'demand': 0.0},
    {'init_node': 5, 'term_node': 6, 'demand': 0.0},
    {'init_node': 5, 'term_node': 7, 'demand': 0.0},
    {'init_node': 5, 'term_node': 8, 'demand': 0.0},
    {'init_node': 5, 'term_node': 9, 'demand': 0.0},
    {'init_node': 6, 'term_node': 1, 'demand': 0.0},
    {'init_node': 6, 'term_node': 2, 'demand': 0.0},
    {'init_node': 6, 'term_node': 3, 'demand': 0.0},
    {'init_node': 6, 'term_node': 4, 'demand': 0.0},
    {'init_node': 6, 'term_node': 5, 'demand': 0.0},
    {'init_node': 6, 'term_node': 6, 'demand': 0.0},
    {'init_node': 6, 'term_node': 7, 'demand': 0.0},
    {'init_node': 6, 'term_node': 8, 'demand': 0.0},
    {'init_node': 6, 'term_node': 9, 'demand': 0.0},
    {'init_node': 7, 'term_node': 1, 'demand': 0.0},
    {'init_node': 7, 'term_node': 2, 'demand': 0.0},
    {'init_node': 7, 'term_node': 3, 'demand': 0.0},
    {'init_node': 7, 'term_node': 4, 'demand': 0.0},
    {'init_node': 7, 'term_node': 5, 'demand': 0.0},
    {'init_node': 7, 'term_node': 6, 'demand': 0.0},
    {'init_node': 7, 'term_node': 7, 'demand': 0.0},
    {'init_node': 7, 'term_node': 8, 'demand': 0.0},
    {'init_node': 7, 'term_node': 9, 'demand': 0.0},
    {'init_node': 8, 'term_node': 1, 'demand': 0.0},
    {'init_node': 8, 'term_node': 2, 'demand': 0.0},
    {'init_node': 8, 'term_node': 3, 'demand': 0.0},
    {'init_node': 8, 'term_node': 4, 'demand': 0.0},
    {'init_node': 8, 'term_node': 5, 'demand': 0.0},
    {'init_node': 8, 'term_node': 6, 'demand': 0.0},
    {'init_node': 8, 'term_node': 7, 'demand': 0.0},
    {'init_node': 8, 'term_node': 8, 'demand': 0.0},
    {'init_node': 8, 'term_node': 9, 'demand': 0.0},
    {'init_node': 9, 'term_node': 1, 'demand': 0.0},
    {'init_node': 9, 'term_node': 2, 'demand': 0.0},
    {'init_node': 9, 'term_node': 3, 'demand': 0.0},
    {'init_node': 9, 'term_node': 4, 'demand': 0.0},
    {'init_node': 9, 'term_node': 5, 'demand': 0.0},
    {'init_node': 9, 'term_node': 6, 'demand': 0.0},
    {'init_node': 9, 'term_node': 7, 'demand': 0.0},
    {'init_node': 9, 'term_node': 8, 'demand': 0.0},
    {'init_node': 9, 'term_node': 9, 'demand': 0.0},
]
